### ISSUE TITLE
Use plugin without using the Mustache plugin

### ISSUE THREAD

**Issue by stakbit** [stakbit/jQuery-Mobile-Listview-Pagination-Plugin#1]
I finally got your JQM Listview Pagination plugin functioning.  The only snag I rant into is it's dependency on Mustache.  I cannot format my data or perform complex logic.  

Any chance you could provide a demo without mustache? I would be happy to pay you for your time, because this plugin does what I need, aside from the Mustache issue.

**Comment by stakbit** [comment]
Here's a revised (untested) solution of the code that does not use the Mustache Javascript library . Basically what it does is instead of returning JSON formatted response, you are returning an HTML formatted response that takes into account the offsets. I have commented this code for all changes:

```
var getNumber = function() {
    return $.ajax({
        type: "post",
        beforeSend: function() { $.mobile.loading( 'show' ) }, //Show spinner
        complete: function() { $.mobile.loading( 'hide' ) }, //Hide spinner
        async: "true", 
        dataType: 'json', // CHANGE "json" TO "html"
        url: serviceURL,
        data: { listomatic: $.mobile.listomatic.prototype.getResults() },       
        success: function(data) {
            if (data) { 
                //var template = $('#numbers-template').html(); // REMOVE THIS LINE
                //var list = Mustache.to_html(template, data); // REMOVE THIS LINE
                $('#listview').empty(); // ADD THIS LINE TO EMPTY THE LIST
                $('#listview').append(data).listview("refresh"); // CHANGE "list" TO "data"
            }
        }
    });
}
```

Now the trick is to change the PHP file to return the paginated list results in HTML format, something like:

```
$perPage    = $_REQUEST['listomatic']['perPage'];
$listOffset = $_REQUEST['listomatic']['listOffset'];
$searchTerm = $_REQUEST['listomatic']['searchTerm'];

if ($searchTerm) {
    $sql = "SELECT * FROM yourTable 
    WHERE date LIKE '%$searchTerm%' 
    ORDER BY date DESC LIMIT $listOffset, $perPage";
    $result = mysqli_query($con, $sql);
} else {
    $sql = "SELECT * FROM yourTable 
    ORDER BY date DESC LIMIT $listOffset, $perPage";
    $result = mysqli_query($con,$sql);
}
// THIS IS THE NEW CHANGE
$html ='';
while ($row = mysql_fetch_row($result)) {
     $html .= '<li>' . $row['your-data'] . '</li>';
}
echo $html;
exit;
```

**Comment by mauiflipper** [comment]
Thank you for the reply. This could be helpful in certain circumstances.  However,  I still want to retrieve the data in JSON format and then perform the logic in javascript. I am trying to avoid doing the logic on the server. This is an example of how I would normally do this is JQM:  (I just don't understand how to implement your plugin into the standard way that JQM does this. Thank you so much for your time.)

$.getJSON(serviceURL + 'getproperties_tablet.php'+ window.location.search, function (data) {
        var employees = data.items;
        $.each(employees, function(index, maui_master) 

if (maui_master.C_LM_Char10_23 == 'Fee Simple') {
var tenure = 'FS'; } else { var tenure = 'LH'; }

var RamDir = maui_master.C_L_ListingID.substr(0, 3);

$('#employeeList').append('&lt;li style=&quot;height: 85px;&quot; id=&quot;ListingRow&quot;&gt;&lt;a href=&quot;MauiPropertyDetails.html?WhatMLS=' + maui_master.C_L_ListingID + '&quot; data-transition=&quot;slide&quot;&gt;' + '&lt;img style=&quot;margin-top: 3px; width: 100px;height: 75px;background-image: url('http://www.domainname.net/NoPhotoSmall.jpg'); border-radius: 6px; -moz-border-radius: 6px; -webkit-border-radius: 6px; border: 1px solid #000000;&quot; src=&quot;http://www.imagedomain.com/MLSImages/' + RamDir + '000/100/maui' + maui_master.C_L_ListingID + '-1.jpg&quot;/&gt;' + '&lt;p style=&quot;font-size: 14px; font-weight:bold;&quot;&gt;' + description + pending + '&lt;/p&gt;&lt;p style=&quot;font-size: 14px;&quot;&gt;' + area + landarea + '&lt;br&gt;' + Rentable + '&lt;/p&gt;&lt;p style=&quot;font-size: 14px;&quot; class=&quot;ui-li-aside&quot;&gt;&lt;strong&gt;$' + addCommas(maui_master.C_L_AskingPrice) + ' ' + tenure + '&lt;/strong&gt;&lt;/p&gt;&lt;/a&gt;&lt;/li&gt;');    

```
    }); // End JSON
```

**Comment by stakbit** [comment]
I updated the Mustache Plugin code sample on the README file to use plain old Javascript and jQuery:

https://github.com/stakbit/jQuery-Mobile-Listview-Pagination-Plugin#register-an-ajax-function

So you'll still be able to use the json data returned from the server.

**Comment by mauiflipper** [comment]
That's the one brah!  Thank you...

**Comment by stakbit** [comment]
Awesome, glad it helped.
