### ISSUE TITLE
Hide "Show More" button when all records are loaded

### ISSUE THREAD

**Issue by stakbit** [stakbit/jQuery-Mobile-Listview-Pagination-Plugin#2]
Make it so that when all found records are loaded, the "Show Me More" button is no longer displayed. This way users don't get to the end and keep clicking on it, wondering why it's not loading any more records.

**Comment by stakbit** [comment]
Completed. The backend must be modified to return the total number of records available (here's a sample):
https://github.com/stakbit/jQuery-Mobile-Listview-Pagination-Plugin#server-side-configuration-to-enable-pagination

Then update the plug-in file: https://github.com/stakbit/jQuery-Mobile-Listview-Pagination-Plugin/blob/master/jquery.mobile.listomatic.js

**Comment by mauiflipper** [comment]
Can I see a sample of what the JSON data is supposed to look like with the new foundRows data?  I am not clear on this new part: 
$aData['total'] = $iFoundRows;

**Comment by stakbit** [comment]
JSON response sample: https://github.com/stakbit/jQuery-Mobile-Listview-Pagination-Plugin/blob/master/README.md#response-data-in-json-format

Make sure to update your sql queries to return the total records available: https://github.com/stakbit/jQuery-Mobile-Listview-Pagination-Plugin#server-side-configuration-to-enable-pagination

**Comment by mauiflipper** [comment]
I updated alll my code and now I get this error after licking on the "Show More" button: TypeError: 'null' is not an object (evaluating 'data.items')

Relevant code section:
var getNumber = function() {
        return $.ajax({
            type: "get",
            beforeSend: function() { $.mobile.loading( 'show' ) }, //Show spinner
            complete: function() { $.mobile.loading( 'hide' ) }, //Hide spinner
            async: "true",
            dataType: 'json',
            url: serviceURL + 'getproperties_tablet_test2.php'+ window.location.search,
            data: { listomatic: $.mobile.listomatic.prototype.getResults() },
            success: function(data) {
// Below line is what I get the error on
                if (data.items) {
                    var list = '';

**Comment by mauiflipper** [comment]
Ah, I see.  When there are no records or there aren't any left to show, the PHP service returns "null", instead of:

{
   "total":"0",
   "numbers":[
      {

```
     }
  },
  {

     }
  }
```

   ]
}

**Comment by mauiflipper** [comment]
OK, I fixed this issue by placing this:

 $aData['total'] = '0'; 

above this line:

while($row = mysqli_fetch_array($result)) {

**Comment by mauiflipper** [comment]
I see one remaining issue.  When the Total Found Count is less than the perPage value, the "show more" button is displayed.

**Comment by stakbit** [comment]
The PHP service should not return "null" for the "total" field, it should always return the total records available (a number).

You should never have to hard code $aData['total'] = '0';  The "0" here should be the actual records available, "0" means that there are no records available, thus the plugin never displays the "Show More" button.

Make sure your sql queries include SQL_CALC_FOUND_ROWS to give you the total records available:
https://github.com/stakbit/jQuery-Mobile-Listview-Pagination-Plugin#server-side-configuration-to-enable-pagination

**Comment by mauiflipper** [comment]
Let me clarify. When the found records are zero, the php service is not returning null for the total field.  Instead it is returning null as the entire response, which is not a valid json response.
