### ISSUE TITLE
Remove refreshContent option

### ISSUE THREAD

**Issue by stakbit** [stakbit/jQuery-Mobile-Listview-Pagination-Plugin#3]
Get rid of the "refreshContent" feature.  Perhaps you can just comment out that portion?

**Comment by stakbit** [comment]
By default if you do not define the refreshContent option, it will not be applied (ie, content will not refresh).

This refreshContent = true option declaration will refresh the content once a day (at midnight local user time):

<pre>
$.extend($.mobile.listomatic.prototype.options, {perPage: 5, btnLabel: 'Show Me More', refreshContent: true});
</pre>

if you do not extend the options (do not include this line, the plugin will use the internal defaults of refreshContent = false, this means do not refresh content) or remove the refreshContent option out all together and include other options.

<pre>
$.extend($.mobile.listomatic.prototype.options, {perPage: 5, btnLabel: 'Show Me More'});
</pre>

You can always programmatically set the refreshContent option to true, thus enabling the daily refresh of content:

**Comment by stakbit** [comment]
Closing issue as there's no need to remove this option as it is, ahem, optional :).

**Comment by mauiflipper** [comment]
Thanks.  That's exactly wat I did.  I was hoping you made it that way.

Daryl
